export type Format = "json" | "text" | "srt" | "vtt" | "csv" | "md";

export interface Segment {
  start: number;
  duration: number;
  text: string;
}

export interface Track {
  languageCode: string;
  languageName: string;
  autoGenerated: boolean;
}

export interface Transcript {
  videoId: string;
  title: string | null;
  author: string | null;
  channelId: string | null;
  durationSeconds: number;
  language: string;
  translated: boolean;
  autoGenerated: boolean;
  source: "captions" | "speech_to_text";
  segments: Segment[];
  text: string;
  availableLanguages: Track[];
}

export interface TranscriptOptions {
  /** BCP-47 code of the caption track to use. */
  language?: string;
  /** BCP-47 code to machine-translate into (150+ languages). */
  translateTo?: string;
  format?: Format;
  /** JSON only: set false to return just the full text. */
  includeSegments?: boolean;
  /** Prefix lines with [HH:MM:SS] in text and md output. */
  timestamps?: boolean;
  /** Merge caption cues into paragraph-length segments. */
  paragraphs?: boolean;
}

export interface Usage {
  plan: string;
  credits_remaining: number;
  plan_credits: { total: number; used: number; remaining: number };
  topup_credits: { remaining: number; grants: Array<{ remaining: number; expires_at: string }> };
  period_resets_at: string | null;
  rate_limit_per_minute: number;
}

export class TranscriptYTError extends Error {
  status?: number;
  /** e.g. INVALID_VIDEO, VIDEO_UNAVAILABLE, NO_CAPTIONS, LANGUAGE_NOT_AVAILABLE, RATE_LIMITED, BLOCKED, QUOTA_EXCEEDED */
  code?: string;
  body?: unknown;
}

export class TranscriptYT {
  constructor(options?: { apiKey?: string; baseUrl?: string; fetch?: typeof fetch });
  getTranscript(url: string, options?: TranscriptOptions & { format?: "json" }): Promise<Transcript>;
  getTranscript(url: string, options: TranscriptOptions & { format: Exclude<Format, "json"> }): Promise<string>;
  listLanguages(url: string): Promise<{ videoId: string; languages: Track[] }>;
  getUsage(): Promise<Usage>;
}

export default TranscriptYT;
